[nfs]
172.31.87.112 ansible_ssh_user='ec2-user'

[webservers]
172.31.82.123 ansible_ssh_user='ec2-user'
172.31.93.51 ansible_ssh_user='ec2-user'

[db]
172.31.94.134 ansible_ssh_user='ec2-user'

[lb]
172.31.94.194 ansible_ssh_user='ubuntu'
